# Generated by Django 2.2.12 on 2020-04-01 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_customtext_ghdgh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='ghdgh',
        ),
    ]
